spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://18.219.190.56:3306/icms?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: icms
        password: icms
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        
chokre:
  pdfTemplate: 
    invoiceWithDetails: C:\medpharm_workspace\sib-service\src\main\resources\templates\invoiceWithDetail.jasper
    invoiceWithoutLetterHeadWithDetails: C:\medpharm_workspace\sib-service\src\main\resources\templates\invoiceWithDetailWithoutHeader.jasper
    invoiceWithoutDetials: C:\medpharm_workspace\sib-service\src\main\resources\templates\invoiceWithoutDetail.jasper
    invoiceWithoutLetterHeadWithoutDetails: C:\medpharm_workspace\sib-service\src\main\resources\templates\invoiceWithOutDetailWithoutHeader.jasper
    paymentProcedure: C:\medpharm_workspace\sib-service\src\main\resources\templates\payment_procedure.jasper
    creditNote: C:\medpharm_workspace\sib-service\src\main\resources\templates\creditNote.jasper
    creditNoteWithoutHeader: C:\medpharm_workspace\sib-service\src\main\resources\templates\creditNoteWithoutLetterHead.jasper



