spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/oauth2?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: root
        password: system
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: create-drop
# --- server
server:
  port: 8083



