spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/oauth2
        username: root
        password: system
#        initialization-mode: always
#    jpa:
#      hibernate:
#        ddl-auto: none
# --- server
server:
  port: 8081



